version: build.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  ETA_VER: v0.7.0
  GITHUB_TOKEN:
    secure: IdgCOIno/YfkZynVnR2pBSjpkNG+4+XZneFXnqBVvxwX3MYX0EKqdzIUVPxQrkJu
  GOPATH: c:\gopath
  TOXENV: py37

init:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    
    echo %GOPATH%

    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
    
    echo %PATH%
    
    python --version
    
    go version

    go env

install:
- ps: >-
    go get github.com/itchio/gothub
    
    echo gothub info -u timetag -r ETA

    python -m pip --version

    python -m pip install wheel --upgrade

    python -m pip install tox --upgrade

    Install-Product node 8 x64

    cd gui

    yarn

    cd ..

cache:
- gui\node_modules
- '%USERPROFILE%\.electron'
- '%LOCALAPPDATA%\electron\Cache'
- '%LOCALAPPDATA%\electron-builder\cache'

build_script:
- cmd: >-
    echo building wheel

    python setup.py bdist_wheel

    echo building GUI
    
    appveyor DownloadFile https://www.python.org/ftp/python/3.7.3/python-3.7.3-amd64-webinstall.exe -FileName %APPVEYOR_BUILD_FOLDER%\gui\python-webinstall.exe

    move %APPVEYOR_BUILD_FOLDER%\dist\*.whl %APPVEYOR_BUILD_FOLDER%\gui\

    cd gui

    yarn dist

    cd ..

    ls %APPVEYOR_BUILD_FOLDER%\gui\dist\

    7z a ETA_Install-win64.zip %APPVEYOR_BUILD_FOLDER%\gui\dist\*.exe

    echo uploading to github

    gothub upload -u timetag -r ETA -t "%ETA_VER%" -f "ETA_Install-win64.zip"  -n "ETA_Install-win64.zip" --replace

test_script:
- cmd: >-
    tox