version: build.{build}
skip_tags: true
image: Visual Studio 2017
init:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    python --version
    
    python -m pip install --disable-pip-version-check --upgrade pip

    python -m pip --version

environment:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHON: C:\Python36-x64
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 64
  GITHUB_TOKEN:
    secure: IdgCOIno/YfkZynVnR2pBSjpkNG+4+XZneFXnqBVvxwX3MYX0EKqdzIUVPxQrkJu

install:
- ps: >-
    Install-Product node 8 x64
    
    npm install -g github-release-cli
    
    python -m pip install pypiwin32 --upgrade
    
    python -m pip install pyinstaller --upgrade 
    
    python -m pip install cffi --upgrade
    
    python -m pip install numpy --upgrade
    
    python -m pip install scipy --upgrade
    
    python -m pip install lmfit --upgrade
    
    python -m pip install astunparse --upgrade
    
    python -m pip install dash --upgrade
    
    python -m pip install dash-renderer --upgrade
    
    python -m pip install dash-html-components --upgrade
    
    python -m pip install dash-core-components --upgrade
    
    python -m pip install plotly --upgrade
    
    python -m pip install bokeh --upgrade
    
    python -m pip install llvmlite --upgrade
    
    python -m pip install numba --upgrade
    
    cd gui

    yarn

    cd ..

cache:
- '%LOCALAPPDATA%\pip\Cache'
- gui\node_modules
- '%USERPROFILE%\.electron'
- '%LOCALAPPDATA%\electron\Cache'
- '%LOCALAPPDATA%\electron-builder\cache'

build_script:
- cmd: >-
    pyinstaller --clean --onefile 
    --add-data "ll/*;ll" 
    --exclude-module numba
    --exclude-module llvmlite
    --exclude-module numpy
    --exclude-module bokeh
    --exclude-module scipy
    --exclude-module flask
    --hidden-import timeit
    --hidden-import http
    --hidden-import http.cookies
    --hidden-import logging.handlers
    --hidden-import logging
    --hidden-import ctypes.wintypes
    --hidden-import colorsys
    --hidden-import csv
    --hidden-import numbers
    --hidden-import gettext
    -i icon.ico  
    ETA.py

    7z a ETA_LIB.zip "c:\python36-x64\lib\site-packages"
    
    move %APPVEYOR_BUILD_FOLDER%\dist\ETA.exe %APPVEYOR_BUILD_FOLDER%\ETABackend.exe
    
    cd gui

    yarn dist

    cd ..
test_script:
- cmd: >-

     
     github-release upload --owner=timetag --repo=ETABackend --tag="%APPVEYOR_BUILD_NUMBER%" --name="%APPVEYOR_BUILD_NUMBER%"  "C:/projects/ETABackend/ETABackend.exe" "C:/projects/ETABackend/ETA_LIB.zip" 