version: build.{build}
skip_tags: true
image: Visual Studio 2017
init:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    
    echo pip install --user --upgrade pip

    python --version
environment:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHON: C:\Python36-x64
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 64
  GITHUB_TOKEN:
    secure: IdgCOIno/YfkZynVnR2pBSjpkNG+4+XZneFXnqBVvxwX3MYX0EKqdzIUVPxQrkJu

install:
- ps: >-
    mkdir c:/whls

    if(!(Test-Path -Path "c:/whls/llvmlite-0.22.0-cp36-cp36m-win_amd64.whl" )){

     appveyor DownloadFile https://github.com/timetag/ETABackend/releases/download/wheels/llvmlite-0.22.0-cp36-cp36m-win_amd64.whl -FileName c:/whls/llvmlite-0.22.0-cp36-cp36m-win_amd64.whl
    
    }
    if(!(Test-Path -Path "c:/whls/numba-0.37.0-cp36-cp36m-win_amd64.whl" )){
    
     appveyor DownloadFile https://github.com/timetag/ETABackend/releases/download/wheels/numba-0.37.0-cp36-cp36m-win_amd64.whl -FileName c:/whls/numba-0.37.0-cp36-cp36m-win_amd64.whl
    
    }
    
    if(!(Test-Path -Path "c:/whls/numpy-1.14.1+mkl-cp36-cp36m-win_amd64.whl" )){
    
     appveyor DownloadFile https://github.com/timetag/ETABackend/releases/download/wheels/numpy-1.14.1.mkl-cp36-cp36m-win_amd64.whl -FileName c:/whls/numpy-1.14.1+mkl-cp36-cp36m-win_amd64.whl
    
    }
    
    pip install pypiwin32
    
    pip install --upgrade pyinstaller
    
    pip install cffi
    
    pip install numpy
    
    pip install scipy
    
    pip install lmfit
    
    pip install astunparse
    
    pip install dash==0.21.0
    
    pip install dash-renderer==0.11.3
    
    pip install dash-html-components==0.9.0
    
    pip install dash-core-components==0.21.0
    
    pip install plotly --upgrade
    
    pip install bokeh --upgrade
    
    pip install c:/whls/llvmlite-0.22.0-cp36-cp36m-win_amd64.whl
    
    pip install c:/whls/numba-0.37.0-cp36-cp36m-win_amd64.whl

cache:
- c:/whls
- '%LOCALAPPDATA%\pip\Cache'

build_script:
- cmd: >-
    pyinstaller --clean --onefile 
    --add-data "ll/*;ll" 
    --exclude-module numba
    --exclude-module llvmlite
    --exclude-module numpy
    --exclude-module scipy
    --exclude-module flask
    --hidden-import timeit
    --hidden-import http
    --hidden-import http.cookies
    -i favicon.ico  
    ETA.py

    7z a ETA_LIB.zip "c:\python36-x64\lib\site-packages"
    
    move %APPVEYOR_BUILD_FOLDER%\dist\ETA.exe %APPVEYOR_BUILD_FOLDER%\ETABackend.exe
  
test_script:
- cmd: >-
     npm install -g github-release-cli
     
     github-release upload --owner=timetag --repo=ETABackend --tag="%APPVEYOR_BUILD_NUMBER%" --name="%APPVEYOR_BUILD_NUMBER%"  "C:/projects/ETABackend/ETABackend.exe"

     echo  "C:/projects/ETABackend/ETA_LIB.zip" 