version: build.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHON: C:\Python36-x64
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 64
  ETA_VER: v0.0.26
  GITHUB_TOKEN:
    secure: IdgCOIno/YfkZynVnR2pBSjpkNG+4+XZneFXnqBVvxwX3MYX0EKqdzIUVPxQrkJu
  GOPATH: c:\gopath


init:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    echo %GOPATH%

    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
    
    python --version
    
    go version

    go env

install:
- ps: >-
   
    go get github.com/itchio/gothub
    
    gothub info -u timetag -r ETA

    Install-Product node 8 x64

    python -m pip install --disable-pip-version-check --upgrade pip

    python -m pip --version

    python -m pip install pypiwin32 --upgrade
    
    python -m pip install matplotlib --upgrade 

    python -m pip install pyinstaller --upgrade 
    
    python -m pip install cffi --upgrade
    
    python -m pip install numpy --upgrade
    
    python -m pip install scipy --upgrade
    
    python -m pip install lmfit --upgrade
    
    python -m pip install astunparse --upgrade
    
    python -m pip install dash --upgrade
    
    python -m pip install dash-renderer --upgrade
    
    python -m pip install dash-html-components --upgrade
    
    python -m pip install dash-core-components --upgrade
    
    python -m pip install plotly --upgrade
    
    python -m pip install bokeh --upgrade
    
    python -m pip install llvmlite --upgrade
    
    python -m pip install numba --upgrade
    
    cd gui

    yarn

    cd ..

cache:
- '%LOCALAPPDATA%\pip\Cache'
- gui\node_modules
- '%USERPROFILE%\.electron'
- '%LOCALAPPDATA%\electron\Cache'
- '%LOCALAPPDATA%\electron-builder\cache'

build_script:
- cmd: >-
    pyinstaller --clean --onefile 
    --add-data "ll/*;ll" 
    --exclude-module numba
    --exclude-module llvmlite
    --exclude-module numpy
    --exclude-module bokeh
    --exclude-module scipy
    --exclude-module flask
    --hidden-import tkinter 
    --hidden-import timeit
    --hidden-import http
    --hidden-import http.cookies
    --hidden-import logging.handlers
    --hidden-import logging
    --hidden-import ctypes.wintypes
    --hidden-import colorsys
    --hidden-import csv
    --hidden-import numbers
    --hidden-import gettext
    -i icon.ico  
    ETA.py

    7z a ETA_LIB.zip "c:\python36-x64\lib\site-packages"
    
    move %APPVEYOR_BUILD_FOLDER%\dist\ETA.exe %APPVEYOR_BUILD_FOLDER%\ETABackend.exe
    
test_script:
- cmd: >-

     cd gui

     yarn dist

     cd ..

     gothub upload -u timetag -r ETA -t "%ETA_VER%" -f "ETABackend.exe" -n "ETABackend.exe" --replace

     gothub upload -u timetag -r ETA -t "%ETA_VER%" -f "ETA_LIB.zip"  -n "ETA_LIB.zip" --replace