version: build.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  ETA_VER: v0.5.11
  GITHUB_TOKEN:
    secure: IdgCOIno/YfkZynVnR2pBSjpkNG+4+XZneFXnqBVvxwX3MYX0EKqdzIUVPxQrkJu
  PYPI_USERNAME:
    secure: +n9bRrcr1wUOt6LkYPOmBw==
  PYPI_PASSWORD:
    secure: yRdmCM7a4/Tg2xMCn38bSc9+xadPa1zVf7FCZtKCsPI=
  GOPATH: c:\gopath


init:
- cmd: >-
    SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    
    echo %GOPATH%

    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
    
    echo %PATH%
    
    python --version
    
    go version

    go env

install:
- ps: >-
    python -m pip --version
    
    pip install --upgrade -r requirements.txt

    7z a ETA_LIB-win64.zip "c:\python37-x64\lib\site-packages"

    go get github.com/itchio/gothub
    
    gothub info -u timetag -r ETA

    python -m pip install pypiwin32 --upgrade
    
    python -m pip install pyinstaller --upgrade

    python -m pip install twine --upgrade
    
    python -m pip install wheel --upgrade
    
    Install-Product node 8 x64
    
    cd gui

    yarn

    cd ..

cache:
- '%LOCALAPPDATA%\pip\Cache'
- gui\node_modules
- '%USERPROFILE%\.electron'
- '%LOCALAPPDATA%\electron\Cache'
- '%LOCALAPPDATA%\electron-builder\cache'

build_script:
- cmd: >-
    echo building backend

    cd etabackend

    pyinstaller --clean --onefile 
    --add-data "ll/*;ll" 
    --exclude-module numba
    --exclude-module llvmlite
    --exclude-module numpy
    --exclude-module bokeh
    --exclude-module scipy
    --exclude-module flask
    --hidden-import pathlib
    --hidden-import tkinter 
    --hidden-import tkinter.filedialog
    --hidden-import tkinter.simpledialog
    --hidden-import timeit
    --hidden-import http
    --hidden-import http.cookies
    --hidden-import logging.handlers
    --hidden-import logging
    --hidden-import ctypes.wintypes
    --hidden-import colorsys
    --hidden-import csv
    --hidden-import numbers
    --hidden-import gettext
    --hidden-import typing
    -i icon.ico  
    ETA.py

    cd ..

    echo building wheel

    python setup.py bdist_wheel

    move %APPVEYOR_BUILD_FOLDER%\etabackend\dist\ETA.exe %APPVEYOR_BUILD_FOLDER%\gui\ETA-Backend.exe
    
    echo building GUI
    
    cd gui

    yarn dist

    cd ..

    ls %APPVEYOR_BUILD_FOLDER%\gui\dist\

    move %APPVEYOR_BUILD_FOLDER%\gui\dist\*.exe %APPVEYOR_BUILD_FOLDER%\
    
    7z a ETA_Install-win64.zip %APPVEYOR_BUILD_FOLDER%\*.exe
    
test_script:
- cmd: >-
    gothub upload -u timetag -r ETA -t "%ETA_VER%" -f "ETA_LIB-win64.zip"  -n "ETA_LIB-win64.zip" --replace
     
    gothub upload -u timetag -r ETA -t "%ETA_VER%" -f "ETA_Install-win64.zip"  -n "ETA_Install-win64.zip" --replace
    
    gothub upload -u timetag -r ETA -t "%ETA_VER%" -f %APPVEYOR_BUILD_FOLDER%\dist\*.whl  -n "ETA_Backend-win64.whl" --replace

    echo twine upload %APPVEYOR_BUILD_FOLDER%\dist\*.whl -u %PYPI_USERNAME% -p %PYPI_PASSWORD% --skip-existing
    
