version: '{branch}.{build}'
skip_tags: true
image: Previous Visual Studio 2017
environment:
  GH_TOKEN:
    secure: IdgCOIno/YfkZynVnR2pBSjpkNG+4+XZneFXnqBVvxwX3MYX0EKqdzIUVPxQrkJu

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node 8 x64
  - yarn


build_script:
  - git submodule update --init --recursive
  - yarn dist

test: off

